import { Link } from 'react-router-dom'
import { Search, Trophy, RotateCcw } from 'lucide-react'
import { useState } from 'react'
import type { CSSProperties } from 'react'
import { games } from '../data'
import { Stat } from '../components/Layout'
import { useGame } from '../context/GameContext'

export function Home() { const [query, setQuery] = useState(''); const { history, achievements } = useGame(); const shown = games.filter(g => g.title.toLowerCase().includes(query.toLowerCase())); return <><section className="hero"><div><p className="eyebrow">YOUR PERSONAL ARCADE</p><h1>Small games.<br /><em>Big fun.</em></h1><p>Pick a game, beat your best, and collect achievements along the way.</p><a href="#games" className="primary">Explore games</a></div><div className="hero-orb"><span>🎮</span><i>✦</i><b>✦</b></div></section><section className="quick"><Stat icon="🎯" value={games.length} label="games to play" /><Stat icon="🏅" value={achievements.filter(a => a.unlocked).length} label="achievements" /><Stat icon="📊" value={history.length} label="games played" /></section><section id="games" className="section-head"><div><p className="eyebrow">CHOOSE YOUR CHALLENGE</p><h2>Featured games</h2></div><label className="search"><Search size={18}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search games..." /></label></section><section className="game-grid">{shown.map(g => <Link to={`/games/${g.id}`} className="game-card" key={g.id} style={{ '--accent': g.accent } as CSSProperties}><div className="game-icon">{g.icon}</div><span className="chip">{g.players}</span><h3>{g.title}</h3><p>{g.description}</p><strong>Play now <span>→</span></strong></Link>)}</section></> }
export function Leaderboard() { const { history } = useGame(); const records = history.length ? history : [{ id: 'a', game: 'Memory Match', result: 'Completed in 12 moves', score: 880, date: 'Sample' }, { id: 'b', game: 'Tic-Tac-Toe', result: 'X wins', score: 100, date: 'Sample' }, { id: 'c', game: 'Number Guessing', result: 'Found in 4 attempts', score: 600, date: 'Sample' }]; return <section className="page"><p className="eyebrow">YOUR PROGRESS</p><h1>Scoreboard</h1><p className="muted">Your latest games and high scores live right here.</p><div className="score-total"><Trophy/> <div><b>{history.reduce((sum, item) => sum + item.score, 0)}</b><span>Total points earned</span></div></div><div className="history">{records.map((r, i) => <article key={r.id}><span className="rank">{i + 1}</span><div><b>{r.game}</b><small>{r.result} · {r.date}</small></div><strong>{r.score} pts</strong></article>)}</div></section> }
export function Achievements() { const { achievements } = useGame(); return <section className="page"><p className="eyebrow">COLLECT THEM ALL</p><h1>Achievements</h1><p className="muted">Complete games and unlock badges to fill your trophy case.</p><div className="achievement-grid">{achievements.map(a => <article className={!a.unlocked ? 'locked' : ''} key={a.id}><span>{a.unlocked ? a.icon : '🔒'}</span><div><h3>{a.title}</h3><p>{a.description}</p></div>{a.unlocked && <b>Unlocked</b>}</article>)}</div></section> }
export function SettingsPage() { const { dark, setDark } = useGame(); const clear = () => { if (confirm('Clear all GameNest scores and achievements?')) { localStorage.removeItem('gamenest-history'); localStorage.removeItem('gamenest-achievements'); location.reload() } }; return <section className="page"><p className="eyebrow">MAKE IT YOURS</p><h1>Settings</h1><div className="settings-card"><div><h3>Appearance</h3><p>Choose the color theme you prefer.</p></div><button className="toggle" onClick={() => setDark(!dark)}><span className={dark ? 'on' : ''}></span>{dark ? 'Dark mode' : 'Light mode'}</button></div><div className="settings-card danger"><div><h3>Reset GameNest</h3><p>Remove your local score history and achievements.</p></div><button onClick={clear}><RotateCcw size={16}/> Reset data</button></div></section> }
