import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'
import { RotateCcw } from 'lucide-react'
import { useGame } from '../context/GameContext'
const Reset = ({ onClick }: { onClick: () => void }) => <button className="secondary" onClick={onClick}><RotateCcw size={16}/> New game</button>

export function TicTacToe() { const [board, setBoard] = useState<string[]>(Array(9).fill('')); const [turn, setTurn] = useState('X'); const [done, setDone] = useState(false); const { addResult } = useGame(); const wins = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]]; const winner = wins.find(([a,b,c]) => board[a] && board[a] === board[b] && board[a] === board[c])?.map(i => board[i])[0]; const draw = !winner && board.every(Boolean); useEffect(() => { if ((winner || draw) && !done) { setDone(true); addResult('Tic-Tac-Toe', winner ? `${winner} wins` : 'Draw', winner ? 100 : 25, winner ? ['ttt-win'] : []) } }, [winner, draw, done, addResult]); const play = (i: number) => { if (board[i] || done) return; setBoard(b => b.map((x, n) => n === i ? turn : x)); setTurn(t => t === 'X' ? 'O' : 'X') }; const reset = () => { setBoard(Array(9).fill('')); setTurn('X'); setDone(false) }; return <div className="game-panel"><div className="game-status">{winner ? <><b>{winner} wins!</b> Great game.</> : draw ? <><b>It’s a draw!</b> Try again?</> : <>Player <b>{turn}</b>’s turn</>}</div><div className="ttt-board">{board.map((v, i) => <button className={v === 'X' ? 'x' : 'o'} onClick={() => play(i)} key={i}>{v}</button>)}</div><Reset onClick={reset}/></div> }
const icons = ['🍒','🍒','🌙','🌙','🚀','🚀','🎲','🎲','🌈','🌈','🎸','🎸']; const shuffle = () => [...icons].sort(() => Math.random() - .5)
export function MemoryMatch() { const [cards, setCards] = useState(shuffle); const [open, setOpen] = useState<number[]>([]); const [matched, setMatched] = useState<number[]>([]); const [moves, setMoves] = useState(0); const [locked, setLocked] = useState(false); const { addResult } = useGame(); const reset = () => { setCards(shuffle()); setOpen([]); setMatched([]); setMoves(0); setLocked(false) }; const flip = (i: number) => { if (locked || open.includes(i) || matched.includes(i)) return; const now = [...open, i]; setOpen(now); if (now.length === 2) { setMoves(x => x + 1); setLocked(true); const isMatch = cards[now[0]] === cards[now[1]]; setTimeout(() => { if (isMatch) setMatched(x => [...x, ...now]); setOpen([]); setLocked(false) }, 650) } }; useEffect(() => { if (matched.length === cards.length && cards.length) addResult('Memory Match', `Completed in ${moves} moves`, Math.max(100, 1200 - moves * 35), ['memory-master']) }, [matched, cards.length, moves, addResult]); return <div className="game-panel"><div className="game-status">Moves: <b>{moves}</b> <span className="right">Pairs: {matched.length / 2}/6</span></div><div className="memory-grid">{cards.map((c, i) => <button key={i} className={open.includes(i) || matched.includes(i) ? 'flipped' : ''} onClick={() => flip(i)}>{open.includes(i) || matched.includes(i) ? c : '?'}</button>)}</div>{matched.length === cards.length && <p className="success">Perfect! You cleared the board.</p>}<Reset onClick={reset}/></div> }
export function NumberGuessing() { const [target, setTarget] = useState(() => Math.ceil(Math.random() * 100)); const [value, setValue] = useState(''); const [message, setMessage] = useState('Pick a number from 1 to 100.'); const [tries, setTries] = useState(0); const [won, setWon] = useState(false); const { addResult } = useGame(); const guess = (e: FormEvent) => { e.preventDefault(); const n = Number(value); if (!n || n < 1 || n > 100 || won) return setMessage('Enter a valid number from 1 to 100.'); const next = tries + 1; setTries(next); setValue(''); if (n === target) { setWon(true); setMessage(`You got it! ${target} was the number.`); addResult('Number Guessing', `Found in ${next} attempts`, Math.max(100, 800 - next * 50), next <= 7 ? ['lucky-seven'] : []) } else setMessage(n < target ? 'Too low — aim higher!' : 'Too high — try lower!') }; const reset = () => { setTarget(Math.ceil(Math.random() * 100)); setTries(0); setWon(false); setValue(''); setMessage('Fresh number picked. Good luck!') }; return <div className="game-panel guess"><div className="number-badge">?</div><h2>Find the secret number</h2><p>{message}</p><form onSubmit={guess}><input type="number" value={value} onChange={e => setValue(e.target.value)} placeholder="Your guess" min="1" max="100" /><button className="primary">Guess</button></form><div className="attempts">Attempts <b>{tries}</b></div><Reset onClick={reset}/></div> }
export function RockPaperScissors() { const choices = [{name:'Rock', icon:'✊'}, {name:'Paper', icon:'✋'}, {name:'Scissors', icon:'✌️'}]; const [text, setText] = useState('Choose your move to begin.'); const [cpu, setCpu] = useState('🤖'); const [score, setScore] = useState({ you: 0, cpu: 0 }); const { addResult } = useGame(); const play = (index: number) => { const c = Math.floor(Math.random() * 3); setCpu(choices[c].icon); if (index === c) return setText(`Both chose ${choices[index].name}. It's a tie!`); const won = (index - c + 3) % 3 === 1; setText(won ? `You win! ${choices[index].name} beats ${choices[c].name}.` : `Computer wins — ${choices[c].name} wins.`); setScore(s => ({ you: s.you + (won ? 1 : 0), cpu: s.cpu + (!won ? 1 : 0) })); if (won) addResult('Rock Paper Scissors', 'Round won', 75, ['rps-streak']) }; return <div className="game-panel rps"><div className="rps-score"><div><b>{score.you}</b><span>You</span></div><strong>VS</strong><div><b>{score.cpu}</b><span>CPU</span></div></div><div className="versus"><span>🙂</span><i>vs</i><span>{cpu}</span></div><p>{text}</p><div className="choice-row">{choices.map((c, i) => <button onClick={() => play(i)} key={c.name}><span>{c.icon}</span>{c.name}</button>)}</div></div> }
